package br.eti.ljr.sn.clientesrv.domain;
// Generated 27 de ago. de 2024 18:00:54 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PedVnd generated by hbm2java
 */
@Entity
@Table(name = "PED_VND")
public class PedVnd implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int codPedVnd;
	private Byte status;
	private Date dataCadastro;
	private Date dataEnvio;
	private Date dataPagamento;
	private Date dataDespacho;
	private Date dataEntrega;
	private Date dataCancelamento;
	private Date dataFinalizacao;
	private String obsCancelamento;
	private Long codTransportadora;
	private String numRastreio;
	private int codLoja;
	private long codColaborador;
	private Long codCliente;
	private BigDecimal valorFrete;
	private String endCep;
	private String endLogradouro;
	private String endNumero;
	private String endComplemento;
	private String endBairro;
	private Integer endCodCidade;
	private String obs;
	private Integer codPedVndMotCanc;
	private Integer codPedVndFrt;
	private BigDecimal codLojaFormaPagamento;
	private Integer codFormaPagamento;

	public PedVnd() {
	}

	@Id

	@Column(name = "COD_PED_VND", unique = true, nullable = false, precision = 9, scale = 0)
	public int getCodPedVnd() {
		return this.codPedVnd;
	}

	public void setCodPedVnd(int codPedVnd) {
		this.codPedVnd = codPedVnd;
	}

	@Column(name = "STATUS", precision = 2, scale = 0)
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_CADASTRO", length = 7)
	public Date getDataCadastro() {
		return this.dataCadastro;
	}

	public void setDataCadastro(Date dataCadastro) {
		this.dataCadastro = dataCadastro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ENVIO", length = 7)
	public Date getDataEnvio() {
		return this.dataEnvio;
	}

	public void setDataEnvio(Date dataEnvio) {
		this.dataEnvio = dataEnvio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_PAGAMENTO", length = 7)
	public Date getDataPagamento() {
		return this.dataPagamento;
	}

	public void setDataPagamento(Date dataPagamento) {
		this.dataPagamento = dataPagamento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_DESPACHO", length = 7)
	public Date getDataDespacho() {
		return this.dataDespacho;
	}

	public void setDataDespacho(Date dataDespacho) {
		this.dataDespacho = dataDespacho;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_ENTREGA", length = 7)
	public Date getDataEntrega() {
		return this.dataEntrega;
	}

	public void setDataEntrega(Date dataEntrega) {
		this.dataEntrega = dataEntrega;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_CANCELAMENTO", length = 7)
	public Date getDataCancelamento() {
		return this.dataCancelamento;
	}

	public void setDataCancelamento(Date dataCancelamento) {
		this.dataCancelamento = dataCancelamento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_FINALIZACAO", length = 7)
	public Date getDataFinalizacao() {
		return this.dataFinalizacao;
	}

	public void setDataFinalizacao(Date dataFinalizacao) {
		this.dataFinalizacao = dataFinalizacao;
	}

	@Column(name = "OBS_CANCELAMENTO", length = 500)
	public String getObsCancelamento() {
		return this.obsCancelamento;
	}

	public void setObsCancelamento(String obsCancelamento) {
		this.obsCancelamento = obsCancelamento;
	}

	@Column(name = "COD_TRANSPORTADORA", precision = 14, scale = 0)
	public Long getCodTransportadora() {
		return this.codTransportadora;
	}

	public void setCodTransportadora(Long codTransportadora) {
		this.codTransportadora = codTransportadora;
	}

	@Column(name = "NUM_RASTREIO", length = 50)
	public String getNumRastreio() {
		return this.numRastreio;
	}

	public void setNumRastreio(String numRastreio) {
		this.numRastreio = numRastreio;
	}

	@Column(name = "COD_LOJA", nullable = false, precision = 9, scale = 0)
	public int getCodLoja() {
		return this.codLoja;
	}

	public void setCodLoja(int codLoja) {
		this.codLoja = codLoja;
	}

	@Column(name = "COD_COLABORADOR", nullable = false, precision = 14, scale = 0)
	public long getCodColaborador() {
		return this.codColaborador;
	}

	public void setCodColaborador(long codColaborador) {
		this.codColaborador = codColaborador;
	}

	@Column(name = "COD_CLIENTE", precision = 14, scale = 0)
	public Long getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(Long codCliente) {
		this.codCliente = codCliente;
	}

	@Column(name = "VALOR_FRETE", precision = 32, scale = 16)
	public BigDecimal getValorFrete() {
		return this.valorFrete;
	}

	public void setValorFrete(BigDecimal valorFrete) {
		this.valorFrete = valorFrete;
	}

	@Column(name = "END_CEP", length = 50)
	public String getEndCep() {
		return this.endCep;
	}

	public void setEndCep(String endCep) {
		this.endCep = endCep;
	}

	@Column(name = "END_LOGRADOURO", length = 200)
	public String getEndLogradouro() {
		return this.endLogradouro;
	}

	public void setEndLogradouro(String endLogradouro) {
		this.endLogradouro = endLogradouro;
	}

	@Column(name = "END_NUMERO", length = 50)
	public String getEndNumero() {
		return this.endNumero;
	}

	public void setEndNumero(String endNumero) {
		this.endNumero = endNumero;
	}

	@Column(name = "END_COMPLEMENTO", length = 50)
	public String getEndComplemento() {
		return this.endComplemento;
	}

	public void setEndComplemento(String endComplemento) {
		this.endComplemento = endComplemento;
	}

	@Column(name = "END_BAIRRO", length = 100)
	public String getEndBairro() {
		return this.endBairro;
	}

	public void setEndBairro(String endBairro) {
		this.endBairro = endBairro;
	}

	@Column(name = "END_COD_CIDADE", precision = 6, scale = 0)
	public Integer getEndCodCidade() {
		return this.endCodCidade;
	}

	public void setEndCodCidade(Integer endCodCidade) {
		this.endCodCidade = endCodCidade;
	}

	@Column(name = "OBS", length = 200)
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@Column(name = "COD_PED_VND_MOT_CANC", precision = 9, scale = 0)
	public Integer getCodPedVndMotCanc() {
		return this.codPedVndMotCanc;
	}

	public void setCodPedVndMotCanc(Integer codPedVndMotCanc) {
		this.codPedVndMotCanc = codPedVndMotCanc;
	}

	@Column(name = "COD_PED_VND_FRT", precision = 9, scale = 0)
	public Integer getCodPedVndFrt() {
		return this.codPedVndFrt;
	}

	public void setCodPedVndFrt(Integer codPedVndFrt) {
		this.codPedVndFrt = codPedVndFrt;
	}

	@Column(name = "COD_LOJA_FORMA_PAGAMENTO", precision = 22, scale = 0)
	public BigDecimal getCodLojaFormaPagamento() {
		return this.codLojaFormaPagamento;
	}

	public void setCodLojaFormaPagamento(BigDecimal codLojaFormaPagamento) {
		this.codLojaFormaPagamento = codLojaFormaPagamento;
	}

	@Column(name = "COD_FORMA_PAGAMENTO", precision = 6, scale = 0)
	public Integer getCodFormaPagamento() {
		return this.codFormaPagamento;
	}

	public void setCodFormaPagamento(Integer codFormaPagamento) {
		this.codFormaPagamento = codFormaPagamento;
	}

}
