package br.eti.ljr.sn.clientesrv.domain;
// Generated 27 de ago. de 2024 18:01:42 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PedVndMotCanc generated by hbm2java
 */
@Entity
@Table(name = "PED_VND_MOT_CANC")
public class PedVndMotCanc implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codPedVndMotCanc;
	private String descricao;
	private Boolean ativo;

	public PedVndMotCanc() {
	}

	@Id

	@Column(name = "COD_PED_VND_MOT_CANC", unique = true, nullable = false, precision = 9, scale = 0)
	public int getCodPedVndMotCanc() {
		return this.codPedVndMotCanc;
	}

	public void setCodPedVndMotCanc(int codPedVndMotCanc) {
		this.codPedVndMotCanc = codPedVndMotCanc;
	}

	@Column(name = "DESCRICAO", length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "ATIVO", precision = 1, scale = 0)
	public Boolean getAtivo() {
		return this.ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

}
