package br.eti.ljr.sn.clientesrv.domain;
// Generated 27 de ago. de 2024 18:01:42 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PedVndProd generated by hbm2java
 */
@Entity
@Table(name = "PED_VND_PROD")
public class PedVndProd implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private PedVndProdId id;
	private int codProduto;
	private int codProdutoDetalhe;
	private int codProdutoDetalheTam;
	private String origem;
	private Integer codLoja;
	private Integer codAtendimento;
	private Integer codAtendimentoProduto;
	private BigDecimal valorUnitarioBruto;
	private BigDecimal valorUnitarioDesconto;
	private BigDecimal quantidade;
	private Integer codOferta;

	public PedVndProd() {
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codPedVnd", column = @Column(name = "COD_PED_VND", nullable = false, precision = 9, scale = 0)),
			@AttributeOverride(name = "codPedVndProd", column = @Column(name = "COD_PED_VND_PROD", nullable = false, precision = 9, scale = 0)) })
	public PedVndProdId getId() {
		return this.id;
	}

	public void setId(PedVndProdId id) {
		this.id = id;
	}

	@Column(name = "COD_PRODUTO", nullable = false, precision = 9, scale = 0)
	public int getCodProduto() {
		return this.codProduto;
	}

	public void setCodProduto(int codProduto) {
		this.codProduto = codProduto;
	}

	@Column(name = "COD_PRODUTO_DETALHE", nullable = false, precision = 9, scale = 0)
	public int getCodProdutoDetalhe() {
		return this.codProdutoDetalhe;
	}

	public void setCodProdutoDetalhe(int codProdutoDetalhe) {
		this.codProdutoDetalhe = codProdutoDetalhe;
	}

	@Column(name = "COD_PRODUTO_DETALHE_TAM", nullable = false, precision = 9, scale = 0)
	public int getCodProdutoDetalheTam() {
		return this.codProdutoDetalheTam;
	}

	public void setCodProdutoDetalheTam(int codProdutoDetalheTam) {
		this.codProdutoDetalheTam = codProdutoDetalheTam;
	}

	@Column(name = "ORIGEM", length = 2)
	public String getOrigem() {
		return this.origem;
	}

	public void setOrigem(String origem) {
		this.origem = origem;
	}

	@Column(name = "COD_LOJA", precision = 9, scale = 0)
	public Integer getCodLoja() {
		return this.codLoja;
	}

	public void setCodLoja(Integer codLoja) {
		this.codLoja = codLoja;
	}

	@Column(name = "COD_ATENDIMENTO", precision = 9, scale = 0)
	public Integer getCodAtendimento() {
		return this.codAtendimento;
	}

	public void setCodAtendimento(Integer codAtendimento) {
		this.codAtendimento = codAtendimento;
	}

	@Column(name = "COD_ATENDIMENTO_PRODUTO", precision = 9, scale = 0)
	public Integer getCodAtendimentoProduto() {
		return this.codAtendimentoProduto;
	}

	public void setCodAtendimentoProduto(Integer codAtendimentoProduto) {
		this.codAtendimentoProduto = codAtendimentoProduto;
	}

	@Column(name = "VALOR_UNITARIO_BRUTO", precision = 32, scale = 16)
	public BigDecimal getValorUnitarioBruto() {
		return this.valorUnitarioBruto;
	}

	public void setValorUnitarioBruto(BigDecimal valorUnitarioBruto) {
		this.valorUnitarioBruto = valorUnitarioBruto;
	}

	@Column(name = "VALOR_UNITARIO_DESCONTO", precision = 32, scale = 16)
	public BigDecimal getValorUnitarioDesconto() {
		return this.valorUnitarioDesconto;
	}

	public void setValorUnitarioDesconto(BigDecimal valorUnitarioDesconto) {
		this.valorUnitarioDesconto = valorUnitarioDesconto;
	}

	@Column(name = "QUANTIDADE", precision = 32, scale = 16)
	public BigDecimal getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(BigDecimal quantidade) {
		this.quantidade = quantidade;
	}

	@Column(name = "COD_OFERTA", precision = 9, scale = 0)
	public Integer getCodOferta() {
		return this.codOferta;
	}

	public void setCodOferta(Integer codOferta) {
		this.codOferta = codOferta;
	}

}
