package br.eti.ljr.sn.clientesrv.domain;
// Generated 27 de ago. de 2024 18:01:42 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PedVndFrt generated by hbm2java
 */
@Entity
@Table(name = "PED_VND_FRT")
public class PedVndFrt implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codPedVndFrt;
	private String descricao;
	private Integer qtdDias;
	private BigDecimal valor;
	private BigDecimal valorFreteGratis;
	private Boolean ativo;

	public PedVndFrt() {
	}

	public PedVndFrt(int codPedVndFrt) {
		this.codPedVndFrt = codPedVndFrt;
	}

	public PedVndFrt(int codPedVndFrt, String descricao, Integer qtdDias, BigDecimal valor, BigDecimal valorFreteGratis,
			Boolean ativo) {
		this.codPedVndFrt = codPedVndFrt;
		this.descricao = descricao;
		this.qtdDias = qtdDias;
		this.valor = valor;
		this.valorFreteGratis = valorFreteGratis;
		this.ativo = ativo;
	}

	@Id

	@Column(name = "COD_PED_VND_FRT", unique = true, nullable = false, precision = 9, scale = 0)
	public int getCodPedVndFrt() {
		return this.codPedVndFrt;
	}

	public void setCodPedVndFrt(int codPedVndFrt) {
		this.codPedVndFrt = codPedVndFrt;
	}

	@Column(name = "DESCRICAO", length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "QTD_DIAS", precision = 9, scale = 0)
	public Integer getQtdDias() {
		return this.qtdDias;
	}

	public void setQtdDias(Integer qtdDias) {
		this.qtdDias = qtdDias;
	}

	@Column(name = "VALOR", precision = 32, scale = 16)
	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@Column(name = "VALOR_FRETE_GRATIS", precision = 32, scale = 16)
	public BigDecimal getValorFreteGratis() {
		return this.valorFreteGratis;
	}

	public void setValorFreteGratis(BigDecimal valorFreteGratis) {
		this.valorFreteGratis = valorFreteGratis;
	}

	@Column(name = "ATIVO", precision = 1, scale = 0)
	public Boolean getAtivo() {
		return this.ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

}
