package br.eti.ljr.sn.clientesrv.domain;
// Generated 27 de ago. de 2024 18:01:42 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PedVndProdId generated by hbm2java
 */
@Embeddable
public class PedVndProdId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codPedVnd;
	private int codPedVndProd;

	public PedVndProdId() {
	}

	public PedVndProdId(int codPedVnd, int codPedVndProd) {
		this.codPedVnd = codPedVnd;
		this.codPedVndProd = codPedVndProd;
	}

	@Column(name = "COD_PED_VND", nullable = false, precision = 9, scale = 0)
	public int getCodPedVnd() {
		return this.codPedVnd;
	}

	public void setCodPedVnd(int codPedVnd) {
		this.codPedVnd = codPedVnd;
	}

	@Column(name = "COD_PED_VND_PROD", nullable = false, precision = 9, scale = 0)
	public int getCodPedVndProd() {
		return this.codPedVndProd;
	}

	public void setCodPedVndProd(int codPedVndProd) {
		this.codPedVndProd = codPedVndProd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PedVndProdId))
			return false;
		PedVndProdId castOther = (PedVndProdId) other;

		return (this.getCodPedVnd() == castOther.getCodPedVnd())
				&& (this.getCodPedVndProd() == castOther.getCodPedVndProd());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodPedVnd();
		result = 37 * result + this.getCodPedVndProd();
		return result;
	}

}
