package br.eti.ljr.sn.clientesrv.domain;
// Generated 15/05/2020 16:28:32 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name = "PRODUTO", schema = "CLICK")
public class Produto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int codigoInt;
	private Integer codigoPesq;
	private String descricao;
	private Boolean ativo;
	private String referencia;
	private BigDecimal precoVenda;
	private BigDecimal precoCusto;
	private BigDecimal icms;
	private BigDecimal pis;
	private BigDecimal cofins;
	private Boolean venda;
	private Boolean brinde;
	private Boolean usoConsumo;

	public Produto() {

	}

	public Produto(int codigoInt) {
		this.codigoInt = codigoInt;
	}

	@Id

	@Column(name = "CODIGO_INT", unique = true, nullable = false, precision = 9, scale = 0)
	public int getCodigoInt() {
		return this.codigoInt;
	}

	public void setCodigoInt(int codigoInt) {
		this.codigoInt = codigoInt;
	}

	@Column(name = "CODIGO_PESQ", precision = 8, scale = 0)
	public Integer getCodigoPesq() {
		return this.codigoPesq;
	}

	public void setCodigoPesq(Integer codigoPesq) {
		this.codigoPesq = codigoPesq;
	}

	@Column(name = "PRECO_CUSTO", precision = 15)
	public BigDecimal getPrecoCusto() {
		return this.precoCusto;
	}

	public void setPrecoCusto(BigDecimal precoCusto) {
		this.precoCusto = precoCusto;
	}

	@Column(name = "DESCRICAO", length = 150)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "ATIVO", precision = 1, scale = 0)
	public Boolean getAtivo() {
		return this.ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

	@Column(name = "REFERENCIA", length = 50)
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Column(name = "PRECO_VENDA", precision = 15)
	public BigDecimal getPrecoVenda() {
		return this.precoVenda;
	}

	public void setPrecoVenda(BigDecimal precoVenda) {
		this.precoVenda = precoVenda;
	}

	@Column(name = "PIS", precision = 2)
	public BigDecimal getPis() {
		return this.pis;
	}

	public void setPis(BigDecimal pis) {
		this.pis = pis;
	}

	@Column(name = "ICMS", precision = 5)
	public BigDecimal getIcms() {
		return this.icms;
	}

	public void setIcms(BigDecimal icms) {
		this.icms = icms;
	}

	@Column(name = "COFINS", precision = 2)
	public BigDecimal getCofins() {
		return this.cofins;
	}

	public void setCofins(BigDecimal cofins) {
		this.cofins = cofins;
	}

	@Column(name = "VENDA", precision = 1, scale = 0)
	public Boolean getVenda() {
		return this.venda;
	}

	public void setVenda(Boolean venda) {
		this.venda = venda;
	}

	@Column(name = "BRINDE", precision = 1, scale = 0)
	public Boolean getBrinde() {
		return this.brinde;
	}

	public void setBrinde(Boolean brinde) {
		this.brinde = brinde;
	}

	@Column(name = "USO_CONSUMO", precision = 1, scale = 0)
	public Boolean getUsoConsumo() {
		return this.usoConsumo;
	}

	public void setUsoConsumo(Boolean usoConsumo) {
		this.usoConsumo = usoConsumo;
	}
}
