package br.eti.ljr.sn.clientesrv.domain;
// Generated 15/05/2020 16:28:32 by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProdutoImg generated by hbm2java
 */
@Entity
@Table(name = "PRODUTO_IMG", schema = "CLICK")
public class ProdutoImg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codProduto;
	private byte[] imagem;
	private Integer verSincEco;

	public ProdutoImg() {
	}

	public ProdutoImg(int codProduto) {
		this.codProduto = codProduto;
	}

	public ProdutoImg(int codProduto, byte[] imagem) {
		this.codProduto = codProduto;
		this.imagem = imagem;
	}

	@Id

	@Column(name = "COD_PRODUTO", unique = true, nullable = false, precision = 9, scale = 0)
	public int getCodProduto() {
		return this.codProduto;
	}

	public void setCodProduto(int codProduto) {
		this.codProduto = codProduto;
	}

	@Column(name = "IMAGEM")
	public byte[] getImagem() {
		return this.imagem;
	}

	public void setImagem(byte[] imagem) {
		this.imagem = imagem;
	}

	@Column(name = "VER_SINC_ECO", precision = 9)
	public Integer getVerSincEco() {
		return verSincEco;
	}

	public void setVerSincEco(Integer verSincEco) {
		this.verSincEco = verSincEco;
	}

}
