package br.eti.ljr.sn.clientesrv.domain;
// Generated 2 de mar. de 2024 11:30:55 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdutoDetalheImagemId generated by hbm2java
 */
@Embeddable
public class ProdutoDetalheImagemId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int codProdDetImagem;
	private int codDetProduto;
	private int codProduto;

	public ProdutoDetalheImagemId() {
	}

	public ProdutoDetalheImagemId(int codProdDetImagem, int codDetProduto, int codProduto) {
		this.codProdDetImagem = codProdDetImagem;
		this.codDetProduto = codDetProduto;
		this.codProduto = codProduto;
	}

	@Column(name = "COD_PROD_DET_IMAGEM", nullable = false, precision = 9, scale = 0)
	public int getCodProdDetImagem() {
		return this.codProdDetImagem;
	}

	public void setCodProdDetImagem(int codProdDetImagem) {
		this.codProdDetImagem = codProdDetImagem;
	}

	@Column(name = "COD_DET_PRODUTO", nullable = false, precision = 6, scale = 0)
	public int getCodDetProduto() {
		return this.codDetProduto;
	}

	public void setCodDetProduto(int codDetProduto) {
		this.codDetProduto = codDetProduto;
	}

	@Column(name = "COD_PRODUTO", nullable = false, precision = 9, scale = 0)
	public int getCodProduto() {
		return this.codProduto;
	}

	public void setCodProduto(int codProduto) {
		this.codProduto = codProduto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdutoDetalheImagemId))
			return false;
		ProdutoDetalheImagemId castOther = (ProdutoDetalheImagemId) other;

		return (this.getCodProdDetImagem() == castOther.getCodProdDetImagem())
				&& (this.getCodDetProduto() == castOther.getCodDetProduto())
				&& (this.getCodProduto() == castOther.getCodProduto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodProdDetImagem();
		result = 37 * result + this.getCodDetProduto();
		result = 37 * result + this.getCodProduto();
		return result;
	}

}
