package br.eti.ljr.sn.clientesrv.domain;
// Generated 2 de mar. de 2024 11:30:55 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ProdutoDetalheImagem generated by hbm2java
 */
@Entity
@Table(name = "PRODUTO_DETALHE_IMAGEM")
public class ProdutoDetalheImagem implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private ProdutoDetalheImagemId id;
	private String nomeArquivo;
	private Boolean ativo;
	private Integer verSincEco;
	private Integer ordem;
	private Long codSite;

	public ProdutoDetalheImagem() {
	}

	public ProdutoDetalheImagem(ProdutoDetalheImagemId id) {
		this.id = id;
	}

	public ProdutoDetalheImagem(ProdutoDetalheImagemId id, String nomeArquivo, Boolean ativo, Integer verSincEco,
			Integer ordem, Long codSite) {
		this.id = id;
		this.nomeArquivo = nomeArquivo;
		this.ativo = ativo;
		this.verSincEco = verSincEco;
		this.ordem = ordem;
		this.codSite = codSite;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codProdDetImagem", column = @Column(name = "COD_PROD_DET_IMAGEM", nullable = false, precision = 9, scale = 0)),
			@AttributeOverride(name = "codDetProduto", column = @Column(name = "COD_DET_PRODUTO", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "codProduto", column = @Column(name = "COD_PRODUTO", nullable = false, precision = 9, scale = 0)) })
	public ProdutoDetalheImagemId getId() {
		return this.id;
	}

	public void setId(ProdutoDetalheImagemId id) {
		this.id = id;
	}

	@Column(name = "NOME_ARQUIVO", length = 100)
	public String getNomeArquivo() {
		return this.nomeArquivo;
	}

	public void setNomeArquivo(String nomeArquivo) {
		this.nomeArquivo = nomeArquivo;
	}

	@Column(name = "ATIVO", precision = 1, scale = 0)
	public Boolean getAtivo() {
		return this.ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

	@Column(name = "VER_SINC_ECO", precision = 9, scale = 0)
	public Integer getVerSincEco() {
		return this.verSincEco;
	}

	public void setVerSincEco(Integer verSincEco) {
		this.verSincEco = verSincEco;
	}

	@Column(name = "ORDEM", precision = 9, scale = 0)
	public Integer getOrdem() {
		return this.ordem;
	}

	public void setOrdem(Integer ordem) {
		this.ordem = ordem;
	}

	@Column(name = "COD_SITE", precision = 14, scale = 0)
	public Long getCodSite() {
		return this.codSite;
	}

	public void setCodSite(Long codSite) {
		this.codSite = codSite;
	}

}
